# Generated by Django 4.1.7 on 2024-12-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_section', '0003_alter_budget_options_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
